### ISSUE TITLE
Don`t updating prices. What i do wrong?

### ISSUE THREAD

**Issue by iLifeHack** [nuadi/googlecrestscript#10]
In function last var =1 and i setup trigger for function one of 5 min , but price in google docs don`t move
but then i manual replaces last var in func and price updating  ... How do what  updating was automatic?
=getMarketPrice(15729;10000002;60003760;"sell";1)

**Comment by iLifeHack** [comment]
first day updating was great, but now prices dont move((

**Comment by nuadi** [comment]
The parameters of the function must be static, or Google will never give you a response for the function.

For example, if you setup the last variable to use a cell that has the function '=now()' inside, it will never return a value because the now() function will update on every onEdit event in the sheet.

You must keep all parameters static.

Now, I should point out that Google will automatically refresh the function every few minutes. I don't know the exact time, but if you sit and watch a cell tracking a volatile market item, the price will go up and down as expected. If you want it to update faster than every few minutes, that's where the refresh parameter comes in - but again, it must be static.
