### ISSUE TITLE
Service invoked too many times for one day: urlfetch

### ISSUE THREAD

**Issue by erikterr** [nuadi/googlecrestscript#36]
Hi, I receive a lot of times the error in object, and of course anything didn't work. I use function getMarketItems with 1000 as parameter. I had around 100 rows for check buy/sell price and volume. How can I fix?
Thanks a lot for your job,

Erik

**Comment by mglinski** [comment]
See: https://developers.google.com/apps-script/guides/services/quotas

You can increase your daily fetch quotas by paying google $5 a month for a Google Apps account and hosting your sheets on that account instead of a free gmail account. This wont increase your total downloaded data cap of 100mb though.
