### ISSUE TITLE
Values returned are "0"

### ISSUE THREAD

**Issue by SubliminallyFamous** [nuadi/googlecrestscript#38]
Hi, following on from our discussion in here: (https://github.com/nuadi/googlecrestscript/issues/11) I've adopted the "getStationMarketPrice" function for loading market prices. At first this worked fine, but now it returns the values as 0 every time. I've tested across three different Google accounts and haven't had the daily quota error once.
Even when attempting to call a single item (it doesn't matter which item I chose) compared to a list of items with the function just repeated for each ID (rather than using the list function) it still results in "0". Not sure if I'm doing something wrong or the Eve servers are throwing the data back as 0 or not. Thanks

Edit: I should also add the "countstationvolume" and "getAverageDailyVolume" are also returning 0's.

**Comment by nuadi** [comment]
Post the exact formula so I can try on my end. However, if they are all returning 0 then it could be a connection problem with the CREST server.

**Comment by SubliminallyFamous** [comment]
Hi Nuadi, I'm using the functions with if statements surrounding them, however if I remove the if statements they still show as 0.
With: `=iferror(getStationMarketPrice(44992,10000002,60003760,"Sell"),"/")`
Without:`=getStationMarketPrice(44992,10000002,60003760,"Sell")`

Another example:
With: `=if($A$2="Off","/",iferror(getStationMarketPrice(B5,10000002,60003760,"Sell"),"/"))`
Without:`=getStationMarketPrice(B5,10000002,60003760,"Sell")`

I have also tried with the optional refresh value set to between 1 and 60, but don't fully understand how this works in relation to Google automatically refreshing them. Is it a second timer that would overwrite the automatic refresh? Thanks

**Comment by SubliminallyFamous** [comment]
I've been doing some poking and have noticed that `=getAverageDailyVolume(10000002,44992,2)` is returning the too many calls per day error whilst the others are returning a 0 value. Could it be that this error is being thrown for the getStationMarketPrice function, but for whatever reason it's returning 0 rather than the error?
I've had the functions cancelled out by an IF statement the whole day, so am surprised it's hit 20,000 already, as I've only had five items listed only when I'm tweaking the spreadsheet, unless they still make the call if they are cancelled out by the IF statement.
I'm cancelling them out with a "Master Switch" in cell A2: `=if($A$2="Off","/",iferror(getStationMarketPrice(B5,10000002,60003760,"Sell"),"/"))`
Would that still cause it to attempt a URLfetch?
Thanks again, apologies if I seem impatient, I've too much time on my hands at the moment!

Update: I made a fresh google account and sheet and **all** functions are working correctly.
On the sheet I'm having issues with I've quite literally got 3000 cells blanked out by the IF statement, but can only assume that the URLFetch is still being made even though the IF statement "forbids" it and the "0" result is in fact a mask for the quota limit error.

**Comment by nuadi** [comment]
Yeah, you're getting 0 instead of the quota error. I don't remember my justification for that, but it needs to be removed. That 0 can also be returned if CREST fails to respond, so it's an ambiguous response at this point.

That is a very interesting observation with the IF functions used to block the calls. I was under the impression that the function would not be called, but it's possible Google still makes the URLFetch to cache the response in case the IF function results in needing that value. I'd have to test that theory out, but it's worth investigating.

No need to apologize about having too much time on your hands. I just have too little to keep up right now. ;)

**Comment by SubliminallyFamous** [comment]
:) I've had the new sheet on the new account running since my last update and have been watching the values refreshing as Google automatically refreshes, what I'm going to do now on yet another fresh account and sheet is have my original layout with all of the IF statements "cancelled" out and then a few of the functions without any to see  if it hit's Google's limits and starts throwing 0's and/or errors at me again.
I'll start with 2000 cells calling each of the four functions, so that *should* be only 8000 URLFetch, allowing space for Google to automatically refresh and we can see if it starts throwing the errors. Theoretically it should load the non "cancelled" values just fine the first time around, but when it refreshes the second time it'll start having trouble.
In regards to the refresh timer you can put into the function (in your examples you use "1") how exactly should this be used? Is it a minute or second timer and would it overrule Google's automatic refresh? Although thinking about it I think even if it did, when the workbook is loaded it'll load fresh data regardless? Cheers

**Comment by nuadi** [comment]
> In regards to the refresh timer you can put into the function (in your examples you use "1") how exactly should this be used? Is it a minute or second timer and would it overrule Google's automatic refresh?

It is not a timer. Think of it like the refresh button in your browser. If the value returned by the function is wrong, and you know it because the in-game price is new, you can change the refresh value and force the function to update.

It's a long story, but Google caches custom function return values, even if the function uses dynamic content. This way, you can force it to refresh. The value itself is never used, so you can use anything so long as you keep changing it and never use the same value twice in a day or two.

**Comment by SubliminallyFamous** [comment]
Ah I understand, thanks. I've got a nifty script that will +1 a specified cell and I can plug a time based trigger onto that if I wanted to.

I've run some tests and noted my progress as I went. Looks like google doesn't cache the "cancelled" data in the background. https://docs.google.com/spreadsheets/d/1nnoVqGAA2-7263E1MgDNPb8g8Z4I9ddp4fdDOQNKYD4/edit?usp=sharing
I had just thought I could place the refresh value in and place that +1 script to get it automatically refreshing, but with the test I did to force it to reload there's no way I didn't hit the 20k limit if it does in fact calculate the "cancelled" cells in the background.
I'm confused now as I didn't get any "0" results either! I guess it's entirely possible CREST was having issues earlier and when I started this testing sheet it decided to play ball.
The only thing I can think of right now is the abnormaly large IF statements I have running on that page that cause sluggishness, but once the page has loaded I would have thought the functions wouldn't have a problem running.

Update:
Guess what? Just threw the master switch on the original sheet again and values are loading (slowly). It's 23:30 local time and I'm pretty sure the google "day" is a few hours behind me, so I have a funny feeling CREST was being difficult today. I'm going to clone the sheet and then remove the if statements I have and find some way to use a vlookup for the particular calls they're trying to specify and have a feeling the sluggishness will ease a little.
Yep. Load times are barely noticeable now. I always knew writing arm-long IF statements was a bad idea. Time to find a work around for how I originally had them.

**Comment by nuadi** [comment]
The source of the 0 price return was within the core of the script where it was failing to get data back from the endpoint. In that event, it would pass an empty string up the chain which was interpreted as a 0 price. As such, I've gutted that portion of the system in the 12a beta, and moving forward you should not get a 0 price any longer. Instead, you will get a raw error message - whatever that may be.

Try out the 12a beta, and let me know if you continue to have issues. Moving forward, I will find a more precise way of handling the errors so that they are more informative than a 0.

**Comment by nuadi** [comment]
Closing this for now just to clean things up. If it continues to be a problem, feel free to open a new ticket or resurrect this one. For now, it should throw a proper error instead of returning zeroes.
